# Generated by Django 4.0.6 on 2022-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationmodel',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100),
        ),
    ]
