# Generated by Django 4.0.6 on 2022-08-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productgallerymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallerymodel',
            options={'verbose_name': 'ProductGalleryModel', 'verbose_name_plural': 'product gallery model'},
        ),
    ]
