# Generated by Django 4.0.6 on 2022-07-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmodel'),
        ('carts', '0003_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variationmodel'),
        ),
    ]
