# Generated by Django 4.0.5 on 2022-06-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'Accounts', 'verbose_name_plural': 'Accounts'},
        ),
    ]
