# Generated by Django 3.1 on 2022-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category_img', models.ImageField(blank=True, upload_to='photos/categories')),
                ('description', models.TextField(blank=True, max_length=350)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
