# Generated by Django 4.0.6 on 2022-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variationmodel_variation_category'),
        ('Order', '0002_remove_order_product_color_remove_order_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='variation',
        ),
        migrations.AddField(
            model_name='order_product',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='store.variationmodel'),
        ),
    ]
