# Generated by Django 4.0.6 on 2022-07-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewrating'),
        ('Order', '0003_remove_order_product_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variationmodel'),
        ),
    ]
